# -*- coding: utf-8 -*-
"""iris

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oho8v_p3prVVSd-FlBG0Sm8oBRmAqb4L
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load data
data = pd.read_excel("IRIS.xlsx")

# input & outpt
X = data.drop("species", axis=1)
y = data["species"]

# Encode the flower names (labels)
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# Build model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Predict and check accuracy
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", round(accuracy * 100, 2), "%")